### PR TITLE
fix: fetch correct open issue count

### PR DESCRIPTION
**Pull request by ephraimduncan**

### CODE REVIEW

**Review by ElTimuro — APPROVED** [review]
- tested locally with render test db, looks good

**Comment by ephraimduncan** [comment]
🫡

**Comment by ElTimuro** [comment]
Feel free to ping me if these things take so long. It's not the culture I want, but just know I want the turnaround on these much faster, especially if I'm the bottleneck

**Comment by ElTimuro** [comment]
deploying now

**Comment by ElTimuro** [comment]
deployed, remove false data for october and re-polled

**Pull request merged**
